### ISSUE TITLE
@TODO Update deps

### ISSUE THREAD

**Issue by aendra-rininsland** [aendrew/generator-strong-d3#4]
The deps in this are probably getting pretty old, particularly around TypeScript. 

List of things to do to update generator to best practices (WIP list)
- [x] Replace tsd with typings ([issue](https://github.com/DefinitelyTyped/tsd/issues/269))
- [x] Provide TypeScript defs for non-vanilla D3 abstractions.
- [x] Integrate typedefs with testing frameworks (See #3).

**Comment by aendrew** [comment]
Updated in adf6ee24d32fa3b9fda8b90073deee2f and 61df9ad4fd8c1b233c35dfb.
